before_script:
  - chmod +x alpine.sh
  - ./alpine.sh
  - gem install bundler --no-document
  - gem install --platform ruby tiny_tds

image: ruby:alpine

test:
  stage: test
  script:
    - bundle install
    - bundle exec cucumber
  artifacts:
    when: always
    paths:
      - log/report.html