source "https://rubygems.org"

gem 'capybara'
gem 'cucumber'
gem 'faker'
gem 'rspec'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'ruby-oci8'
gem 'ruby-mysql'
gem 'pg'
gem 'rake'
gem 'httparty'
gem 'report_builder'
#gem 'parallel_tests'